env:
  global:
    - CC_TEST_REPORTER_ID=80c82c8467064b27592cc027e12ae1b130d9f4c32f4600f59523844b27d48096

language: python
python:
  # we want to test our package on several versions of Python
  - 3.6
  - 3.7
  - 3.8

before_install:
  # make depends on poetry
  - pip install --upgrade pip
  - pip install poetry

install:
  - make install

script:
  - make lint
  - make test

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script: 
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
